---

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    uses: danieljtrowbridge/hs-config/.github/workflows/lint.yaml@main
    with:
      docker-tag: 9.4.6
      package: mutu
  test:
    uses: danieljtrowbridge/hs-config/.github/workflows/test.yaml@main
    with:
      ghc-version: 9.4.6
      package: mutu
