---

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    permissions:
      id-token: write
      pages: write
    uses: danieljtrowbridge/hs-config/.github/workflows/ci_docs.yaml@main
    with:
      ghc-version: 9.4.6
      package: mutu
