---

name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    uses: danieljtrowbridge/hs-config/.github/workflows/test.yaml@main
    with:
      ghc-version: 9.4.6
      package: mutu
